global:
  scrape_interval: 15s

rule_files:
  - '/etc/prometheus/alerts/alert.rules'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

#scrape_configs:
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Используем модуль для HTTP-проверок
    static_configs:
      - targets:
        - https://lms.skillfactory.ru  # Проверяемый URL
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Адрес Blackbox Exporter

  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [http_cert]  # Модуль для проверки SSL
    static_configs:
      - targets:
        - https://lms.skillfactory.ru
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115